/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package docklandssmartpark;

/**
 *
 * @author huynhlehoang
 */
public class DocklandsSmartParkGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DocklandsSmartParkGUI.class.getName());

    /**
     * Creates new form DocklandsSmartParkGUI
     */
    public DocklandsSmartParkGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        docklandssmartparkLbl = new javax.swing.JLabel();
        carRB = new javax.swing.JRadioButton();
        electriccarRB = new javax.swing.JRadioButton();
        motorbikeRB = new javax.swing.JRadioButton();
        vehicleidLbl = new javax.swing.JLabel();
        ownernameLbl = new javax.swing.JLabel();
        slotidLbl = new javax.swing.JLabel();
        slotidupdateLbl = new javax.swing.JLabel();
        vehicleidTF = new javax.swing.JTextField();
        ownernameTF = new javax.swing.JTextField();
        slotidTF = new javax.swing.JTextField();
        slotidupdateTF = new javax.swing.JTextField();
        carquestionLbl = new javax.swing.JLabel();
        electriccarquestionLbl = new javax.swing.JLabel();
        motorbikequestionLbl = new javax.swing.JLabel();
        carquestionTF = new javax.swing.JTextField();
        electriccarquestionTF = new javax.swing.JTextField();
        motorbikequestionTF = new javax.swing.JTextField();
        addslotBtn = new javax.swing.JButton();
        findslotBtn = new javax.swing.JButton();
        removeslotBtn = new javax.swing.JButton();
        updateslotBtn = new javax.swing.JButton();
        addtoqueueBtn = new javax.swing.JButton();
        processqueueBtn = new javax.swing.JButton();
        getoccupiedcountBtn = new javax.swing.JButton();
        displayTA = new javax.swing.JTextArea();
        gethistoryBtn = new javax.swing.JButton();
        checkinBtn = new javax.swing.JButton();
        checkoutBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        imagesSP = new javax.swing.JScrollPane();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 550));
        setPreferredSize(new java.awt.Dimension(550, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        docklandssmartparkLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        docklandssmartparkLbl.setText("DOCKLANDS SMART PARK");
        getContentPane().add(docklandssmartparkLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        carRB.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        carRB.setText("Car");
        getContentPane().add(carRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        electriccarRB.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        electriccarRB.setText("Electric Car");
        getContentPane().add(electriccarRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        motorbikeRB.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        motorbikeRB.setText("Motorbike");
        getContentPane().add(motorbikeRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        vehicleidLbl.setText("Vehicle ID:");
        getContentPane().add(vehicleidLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        ownernameLbl.setText("Owner name:");
        getContentPane().add(ownernameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        slotidLbl.setText("Slot ID:");
        getContentPane().add(slotidLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        slotidupdateLbl.setText("Slot ID update:");
        getContentPane().add(slotidupdateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));
        getContentPane().add(vehicleidTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 150, -1));
        getContentPane().add(ownernameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 150, -1));
        getContentPane().add(slotidTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 150, -1));
        getContentPane().add(slotidupdateTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 150, -1));

        carquestionLbl.setText("Number of seats:");
        getContentPane().add(carquestionLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        electriccarquestionLbl.setText("Battery level (%):");
        getContentPane().add(electriccarquestionLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        motorbikequestionLbl.setText("Engine size (cc):");
        getContentPane().add(motorbikequestionLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));
        getContentPane().add(carquestionTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 120, -1));
        getContentPane().add(electriccarquestionTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 120, -1));
        getContentPane().add(motorbikequestionTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 120, -1));

        addslotBtn.setText("Add slot");
        getContentPane().add(addslotBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 120, 25));

        findslotBtn.setText("Find slot");
        getContentPane().add(findslotBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 120, 25));

        removeslotBtn.setText("Remove slot");
        getContentPane().add(removeslotBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 120, 25));

        updateslotBtn.setText("Update slot");
        getContentPane().add(updateslotBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 120, 25));

        addtoqueueBtn.setText("Add to queue");
        getContentPane().add(addtoqueueBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 150, 25));

        processqueueBtn.setText("Process queue");
        getContentPane().add(processqueueBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 150, 25));

        getoccupiedcountBtn.setText("Get occupied count");
        getContentPane().add(getoccupiedcountBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 150, 25));

        displayTA.setColumns(20);
        displayTA.setRows(5);
        getContentPane().add(displayTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 240, 230));

        gethistoryBtn.setText("Get history");
        getContentPane().add(gethistoryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 150, 25));

        checkinBtn.setText("Check in");
        getContentPane().add(checkinBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 120, 25));

        checkoutBtn.setText("Check out");
        getContentPane().add(checkoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 120, 25));

        exitBtn.setText("Exit");
        getContentPane().add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 120, 25));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        background.setPreferredSize(new java.awt.Dimension(700, 550));
        imagesSP.setViewportView(background);

        getContentPane().add(imagesSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 570, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DocklandsSmartParkGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addslotBtn;
    private javax.swing.JButton addtoqueueBtn;
    private javax.swing.JLabel background;
    private javax.swing.JRadioButton carRB;
    private javax.swing.JLabel carquestionLbl;
    private javax.swing.JTextField carquestionTF;
    private javax.swing.JButton checkinBtn;
    private javax.swing.JButton checkoutBtn;
    private javax.swing.JTextArea displayTA;
    private javax.swing.JLabel docklandssmartparkLbl;
    private javax.swing.JRadioButton electriccarRB;
    private javax.swing.JLabel electriccarquestionLbl;
    private javax.swing.JTextField electriccarquestionTF;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton findslotBtn;
    private javax.swing.JButton gethistoryBtn;
    private javax.swing.JButton getoccupiedcountBtn;
    private javax.swing.JScrollPane imagesSP;
    private javax.swing.JRadioButton motorbikeRB;
    private javax.swing.JLabel motorbikequestionLbl;
    private javax.swing.JTextField motorbikequestionTF;
    private javax.swing.JLabel ownernameLbl;
    private javax.swing.JTextField ownernameTF;
    private javax.swing.JButton processqueueBtn;
    private javax.swing.JButton removeslotBtn;
    private javax.swing.JLabel slotidLbl;
    private javax.swing.JTextField slotidTF;
    private javax.swing.JLabel slotidupdateLbl;
    private javax.swing.JTextField slotidupdateTF;
    private javax.swing.JButton updateslotBtn;
    private javax.swing.JLabel vehicleidLbl;
    private javax.swing.JTextField vehicleidTF;
    // End of variables declaration//GEN-END:variables
}
