/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package docklandssmartpark;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;

/**
 *
 * @author huynhlehoang
 */
public class DocklandsSmartParkGUI extends javax.swing.JFrame {
    
    ParkingLotManager manager;//declare ParkingLotManager of manager objects
    int numSeats, batteryLevel, engineSize;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DocklandsSmartParkGUI.class.getName());

    /**
     * Creates new form DocklandsSmartParkGUI
     */
    public DocklandsSmartParkGUI() {
        initComponents();
        //Automatic line break when the horizontal dimension is reached (reference: https://stackoverflow.com/questions/26420428/how-to-word-wrap-text-in-jlabel): https://stackoverflow.com/questions/26420428/how-to-word-wrap-text-in-jlabel): https://stackoverflow.com/questions/26420428/how-to-word-wrap-text-in-jlabel)
        displayTA.setLineWrap(true);

        //Ensure no word breaks midway (reference: https://stackoverflow.com/questions/26420428/how-to-word-wrap-text-in-jlabel)
        displayTA.setWrapStyleWord(true);
        
        manager = new ParkingLotManager();//create ParkingLotManager empty
        carquestionLbl.setVisible(false);
        carquestionTF.setVisible(false);
        electriccarquestionLbl.setVisible(false);
        electriccarquestionTF.setVisible(false);
        motorbikequestionLbl.setVisible(false);
        motorbikequestionTF.setVisible(false);
        load(); //load data
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vehicleBG = new javax.swing.ButtonGroup();
        docklandssmartparkLbl = new javax.swing.JLabel();
        carRB = new javax.swing.JRadioButton();
        electriccarRB = new javax.swing.JRadioButton();
        motorbikeRB = new javax.swing.JRadioButton();
        vehicleidLbl = new javax.swing.JLabel();
        ownernameLbl = new javax.swing.JLabel();
        slotidLbl = new javax.swing.JLabel();
        slotidupdateLbl = new javax.swing.JLabel();
        vehicleidTF = new javax.swing.JTextField();
        ownernameTF = new javax.swing.JTextField();
        slotidTF = new javax.swing.JTextField();
        slotidupdateTF = new javax.swing.JTextField();
        carquestionLbl = new javax.swing.JLabel();
        electriccarquestionLbl = new javax.swing.JLabel();
        motorbikequestionLbl = new javax.swing.JLabel();
        carquestionTF = new javax.swing.JTextField();
        electriccarquestionTF = new javax.swing.JTextField();
        motorbikequestionTF = new javax.swing.JTextField();
        addslotBtn = new javax.swing.JButton();
        findslotBtn = new javax.swing.JButton();
        removeslotBtn = new javax.swing.JButton();
        updateslotBtn = new javax.swing.JButton();
        addtoqueueBtn = new javax.swing.JButton();
        processqueueBtn = new javax.swing.JButton();
        getoccupiedcountBtn = new javax.swing.JButton();
        displayTA = new javax.swing.JTextArea();
        gethistoryBtn = new javax.swing.JButton();
        checkinBtn = new javax.swing.JButton();
        checkoutBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        imagesSP = new javax.swing.JScrollPane();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 550));
        setPreferredSize(new java.awt.Dimension(550, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        docklandssmartparkLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        docklandssmartparkLbl.setText("DOCKLANDS SMART PARK");
        getContentPane().add(docklandssmartparkLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        vehicleBG.add(carRB);
        carRB.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        carRB.setText("Car");
        carRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carRBActionPerformed(evt);
            }
        });
        getContentPane().add(carRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        vehicleBG.add(electriccarRB);
        electriccarRB.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        electriccarRB.setText("Electric Car");
        electriccarRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electriccarRBActionPerformed(evt);
            }
        });
        getContentPane().add(electriccarRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        vehicleBG.add(motorbikeRB);
        motorbikeRB.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        motorbikeRB.setText("Motorbike");
        motorbikeRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motorbikeRBActionPerformed(evt);
            }
        });
        getContentPane().add(motorbikeRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        vehicleidLbl.setText("Vehicle ID:");
        getContentPane().add(vehicleidLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        ownernameLbl.setText("Owner name:");
        getContentPane().add(ownernameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        slotidLbl.setText("Slot ID:");
        getContentPane().add(slotidLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        slotidupdateLbl.setText("Slot ID update:");
        getContentPane().add(slotidupdateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));
        getContentPane().add(vehicleidTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 150, -1));
        getContentPane().add(ownernameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 150, -1));
        getContentPane().add(slotidTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 150, -1));
        getContentPane().add(slotidupdateTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 150, -1));

        carquestionLbl.setText("Number of seats:");
        getContentPane().add(carquestionLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        electriccarquestionLbl.setText("Battery level (%):");
        getContentPane().add(electriccarquestionLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        motorbikequestionLbl.setText("Engine size (cc):");
        getContentPane().add(motorbikequestionLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));
        getContentPane().add(carquestionTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 120, -1));
        getContentPane().add(electriccarquestionTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 120, -1));
        getContentPane().add(motorbikequestionTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 120, -1));

        addslotBtn.setText("Add slot");
        addslotBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addslotBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addslotBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 120, 25));

        findslotBtn.setText("Find slot");
        findslotBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findslotBtnActionPerformed(evt);
            }
        });
        getContentPane().add(findslotBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 120, 25));

        removeslotBtn.setText("Remove slot");
        removeslotBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeslotBtnActionPerformed(evt);
            }
        });
        getContentPane().add(removeslotBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 120, 25));

        updateslotBtn.setText("Update slot");
        updateslotBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateslotBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateslotBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 120, 25));

        addtoqueueBtn.setText("Add to queue");
        addtoqueueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtoqueueBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addtoqueueBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 150, 25));

        processqueueBtn.setText("Process queue");
        processqueueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processqueueBtnActionPerformed(evt);
            }
        });
        getContentPane().add(processqueueBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 150, 25));

        getoccupiedcountBtn.setText("Get occupied count");
        getoccupiedcountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getoccupiedcountBtnActionPerformed(evt);
            }
        });
        getContentPane().add(getoccupiedcountBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 150, 25));

        displayTA.setColumns(20);
        displayTA.setRows(5);
        getContentPane().add(displayTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 240, 230));

        gethistoryBtn.setText("Get history");
        gethistoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gethistoryBtnActionPerformed(evt);
            }
        });
        getContentPane().add(gethistoryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 150, 25));

        checkinBtn.setText("Check in");
        checkinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkinBtnActionPerformed(evt);
            }
        });
        getContentPane().add(checkinBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 120, 25));

        checkoutBtn.setText("Check out");
        checkoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(checkoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 120, 25));

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 120, 25));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        background.setPreferredSize(new java.awt.Dimension(700, 550));
        imagesSP.setViewportView(background);

        getContentPane().add(imagesSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 570, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void save(){
        
        try(ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("parking.dat"))){
            oos.writeObject(manager);
            JOptionPane.showMessageDialog(this,"Saved parking.dat successfully" );
        }catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving file " + e.getMessage());
        }
    }
    
    private void load(){
        try(ObjectInputStream ois = new ObjectInputStream(new FileInputStream("parking.dat"))){ //open file to read
            manager = (ParkingLotManager)ois.readObject(); // read data and put result in the parkingSlot
            JOptionPane.showMessageDialog(this, "File loaded successfully"); // show message
        } catch (FileNotFoundException e) { //file not found
            
        } catch (ClassNotFoundException e) { // class not found (changed name)
            JOptionPane.showMessageDialog(this, "An error occurred while reading the file. Make sure the class matches the saved data");
        } catch (IOException e) { //file wrong, wrong format..null
            JOptionPane.showMessageDialog(this, "An error occurred while reading the file." + e.getMessage());
            manager = new ParkingLotManager();//if don't have file ==> create list empty to avoid 
        }
    }
    
    private void addslotBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addslotBtnActionPerformed
        // TODO add your handling code here:
        //get Slot ID from slotidTF
        String slotID = slotidTF.getText().trim();
        
        //check empty
        if (slotID.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please enter Slot ID");
            return;
        }else{
            String result = manager.addSlot(slotID);
            displayTA.setText(result);
            slotidTF.setText("");
            ownernameTF.setText("");
            vehicleidTF.setText("");
            carquestionTF.setText("");
            electriccarquestionTF.setText("");
            motorbikequestionTF.setText("");
            save();
        }
    }//GEN-LAST:event_addslotBtnActionPerformed

    private void findslotBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findslotBtnActionPerformed
        // TODO add your handling code here:
        //get Slot ID from slotidTF
        String slotID = slotidTF.getText().trim();
        
        //check empty
        if (slotID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a Slot ID to search.");
            return;
        }else{
            String result = manager.findSlot(slotID);
            displayTA.setText(result);
            slotidTF.setText("");
        }
    }//GEN-LAST:event_findslotBtnActionPerformed

    private void removeslotBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeslotBtnActionPerformed
        // TODO add your handling code here:
        //get Slot ID need to remove
        String slotID = slotidTF.getText().trim();
        
        //check empty
        if (slotID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a Slot ID to remove");
            return;
        }else{
            String result = manager.removeSlot(slotID);
            displayTA.setText(result);
            slotidTF.setText("");
            save();
        }
    }//GEN-LAST:event_removeslotBtnActionPerformed

    private void updateslotBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateslotBtnActionPerformed
        // TODO add your handling code here:
        // get current slotID what you want to update
        String oldID = slotidTF.getText().trim();
        String newID =slotidupdateTF.getText().trim();
        
        //check empty
        if (oldID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the Slot ID now");
            return;
        }
        if (newID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the Slot ID you want to update");
            return;
        }
        String result = manager.updateSlot(oldID, newID);
        displayTA.setText(result);
        slotidTF.setText("");
        slotidupdateTF.setText("");
        save();
    }//GEN-LAST:event_updateslotBtnActionPerformed

    private void checkinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkinBtnActionPerformed
        // TODO add your handling code here:
        String vehicleID = vehicleidTF.getText().trim();//get data and trim space
        String ownerName = ownernameTF.getText().trim();//get data and trim space
        String slotID = slotidTF.getText().trim();//get data and trim space
        
         //check empty 
        if (vehicleID.isEmpty() || ownerName.isEmpty() || slotID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter all fields");
            return;
        }
        //identify vehicle by radio 
        Vehicle v;
        if (carRB.isSelected()){
            //check empty 
            if (carquestionTF.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter number of seats");
                return;
            }
            // Car(int numSeats, String vehicleID, String ownerName)
            numSeats = Integer.parseInt(carquestionTF.getText().trim());
            v = new Car(numSeats, vehicleID, ownerName);
        }else if (electriccarRB.isSelected()){
            //check empty 
            if (electriccarquestionTF.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter battery level (%)");
                return;
            }
            // ElectricCar(int batteryLevel, String vehicleID, String ownerName)
            batteryLevel = Integer.parseInt(electriccarquestionTF.getText().trim());
            v = new ElectricCar (batteryLevel, vehicleID, ownerName);
        }else if(motorbikeRB.isSelected()){
            //check empty 
            if (motorbikequestionTF.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter engine size (cc)");
                return;
            }
            // Motorbike(int engineSize, String vehicleID, String ownerName)
            engineSize = Integer.parseInt(motorbikequestionTF.getText().trim());
            v = new Motorbike (engineSize, vehicleID, ownerName);
        }else{
            JOptionPane.showMessageDialog(this, "Please select a vehicle type");
            return;
        }
        
        boolean checkIn = false;
        SinglyLinkedList slotList = manager.getSlotList();
        //use loop for
        for (int i = 1; i <= slotList.size(); i++){
            ParkingSlot currSlot = (ParkingSlot) slotList.get(i);
            
            if(currSlot.getSlotID().equalsIgnoreCase(slotID)){
                //check isOccupied
                if(currSlot.isOccupied()){
                    JOptionPane.showMessageDialog(this,"Slot " + slotID + " is occupied already! Please add another slot");
                    return;
                }else{
                    currSlot.setVehicle(v);
                    currSlot.setOccupied(true);
                    checkIn = true;
                    break;
                }
            }
        }
        //progress the result
        if(checkIn == true){
            manager.getHistoryStack().push("check in: vehicle "+vehicleID + ", Slot "+ slotID);
            save();
            //display result
            displayTA.setText("Checkin successfully slot: " + slotID + "\n"
                    + "Vehicle ID: " + vehicleID + "\n"
                    + "Owner: " + ownerName + "\n"
                    + "Type: " + v.getParkingCategory() + "\n");
            slotidTF.setText("");
            ownernameTF.setText("");
            vehicleidTF.setText("");
            carquestionTF.setText("");
            electriccarquestionTF.setText("");
            motorbikequestionTF.setText("");
        }else{
            JOptionPane.showMessageDialog(this, "Slot ID " + slotID + " does not exist");
        }
    }//GEN-LAST:event_checkinBtnActionPerformed

    private void checkoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutBtnActionPerformed
        // TODO add your handling code here:
        String slotID = slotidTF.getText().trim();
        //check empty
        if(slotID.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please enter Slot ID");
            return;
        }
        boolean found = false;
        SinglyLinkedList slotList = manager.getSlotList();
        // find the slot 
        for (int i = 1; i <= slotList.size(); i++){
            ParkingSlot currSlot = (ParkingSlot) slotList.get(i);
            if(currSlot.getSlotID().equalsIgnoreCase(slotID)){
                found = true;
                //check isOccupied
                if (currSlot.isOccupied() == false) {
                JOptionPane.showMessageDialog(this, "This slot is empty!");
                return;
                }
                Vehicle v = currSlot.getVehicle();
                currSlot.setVehicle(null);
                currSlot.setOccupied(false);
                // save historyStack
                manager.getHistoryStack().push("Check out: Vehicle "+v.getVehicleID()+" left slot "+slotID);
                displayTA.setText("Slot "+slotID+ " is empty now");
                save();
                slotidTF.setText("");
                break;
            }
        }
        if (found == false) {
            JOptionPane.showMessageDialog(this, "Slot " + slotID + " not found.");
        }
    }//GEN-LAST:event_checkoutBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void addtoqueueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtoqueueBtnActionPerformed
        // TODO add your handling code here:
         //the same check in because addToQueue also needs to know which vehicles (vehicle's information) to add to the queue
        String vehicleID = vehicleidTF.getText().trim();//get data and trim space
        String ownerName = ownernameTF.getText().trim();//get data and trim space
        
         //check empty 
        if (vehicleID.isEmpty() || ownerName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter all fields");
            return;
        }
        //identify vehicle by radio 
        Vehicle v;
        if (carRB.isSelected()){
            //check empty 
            if (carquestionTF.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter number of seats");
                return;
            }
            // Car(int numSeats, String vehicleID, String ownerName)
            numSeats = Integer.parseInt(carquestionTF.getText().trim());
            v = new Car(numSeats, vehicleID, ownerName);
        }else if (electriccarRB.isSelected()){
            //check empty 
            if (electriccarquestionTF.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter battery level (%)");
                return;
            }
            // ElectricCar(int batteryLevel, String vehicleID, String ownerName)
            batteryLevel = Integer.parseInt(electriccarquestionTF.getText().trim());
            v = new ElectricCar (batteryLevel, vehicleID, ownerName);
        }else if(motorbikeRB.isSelected()){
            //check empty 
            if (motorbikequestionTF.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter engine size (cc)");
                return;
            }
            // Motorbike(int engineSize, String vehicleID, String ownerName)
            engineSize = Integer.parseInt(motorbikequestionTF.getText().trim());
            v = new Motorbike (engineSize, vehicleID, ownerName);
        }else{
            JOptionPane.showMessageDialog(this, "Please select a vehicle type");
            return;
        }
        String result = manager.addToQueue(v);
        displayTA.setText(result);
        slotidTF.setText("");
        ownernameTF.setText("");
        vehicleidTF.setText("");
        carquestionTF.setText("");
        electriccarquestionTF.setText("");
        motorbikequestionTF.setText("");
        save();
    }//GEN-LAST:event_addtoqueueBtnActionPerformed

    private void processqueueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processqueueBtnActionPerformed
        // TODO add your handling code here:
        String result = manager.processQueue();
        displayTA.setText(result);
        slotidTF.setText("");
        ownernameTF.setText("");
        vehicleidTF.setText("");
        carquestionTF.setText("");
        electriccarquestionTF.setText("");
        motorbikequestionTF.setText("");
    }//GEN-LAST:event_processqueueBtnActionPerformed

    private void getoccupiedcountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getoccupiedcountBtnActionPerformed
        // TODO add your handling code here:
        String result = manager.getOccupiedCount();
        displayTA.setText(result);
    }//GEN-LAST:event_getoccupiedcountBtnActionPerformed

    private void gethistoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gethistoryBtnActionPerformed
        // TODO add your handling code here:
        String result = manager.getHistory();
        displayTA.setText(result);
    }//GEN-LAST:event_gethistoryBtnActionPerformed

    private void carRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carRBActionPerformed
        // TODO add your handling code here:
        carquestionLbl.setVisible(true);
        carquestionTF.setVisible(true);
        electriccarquestionLbl.setVisible(false);
        electriccarquestionTF.setVisible(false);
        motorbikequestionLbl.setVisible(false);
        motorbikequestionTF.setVisible(false);
    }//GEN-LAST:event_carRBActionPerformed

    private void electriccarRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electriccarRBActionPerformed
        // TODO add your handling code here:
        carquestionLbl.setVisible(false);
        carquestionTF.setVisible(false);
        electriccarquestionLbl.setVisible(true);
        electriccarquestionTF.setVisible(true);
        motorbikequestionLbl.setVisible(false);
        motorbikequestionTF.setVisible(false);
    }//GEN-LAST:event_electriccarRBActionPerformed

    private void motorbikeRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motorbikeRBActionPerformed
        // TODO add your handling code here:
        carquestionLbl.setVisible(false);
        carquestionTF.setVisible(false);
        electriccarquestionLbl.setVisible(false);
        electriccarquestionTF.setVisible(false);
        motorbikequestionLbl.setVisible(true);
        motorbikequestionTF.setVisible(true);
    }//GEN-LAST:event_motorbikeRBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DocklandsSmartParkGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addslotBtn;
    private javax.swing.JButton addtoqueueBtn;
    private javax.swing.JLabel background;
    private javax.swing.JRadioButton carRB;
    private javax.swing.JLabel carquestionLbl;
    private javax.swing.JTextField carquestionTF;
    private javax.swing.JButton checkinBtn;
    private javax.swing.JButton checkoutBtn;
    private javax.swing.JTextArea displayTA;
    private javax.swing.JLabel docklandssmartparkLbl;
    private javax.swing.JRadioButton electriccarRB;
    private javax.swing.JLabel electriccarquestionLbl;
    private javax.swing.JTextField electriccarquestionTF;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton findslotBtn;
    private javax.swing.JButton gethistoryBtn;
    private javax.swing.JButton getoccupiedcountBtn;
    private javax.swing.JScrollPane imagesSP;
    private javax.swing.JRadioButton motorbikeRB;
    private javax.swing.JLabel motorbikequestionLbl;
    private javax.swing.JTextField motorbikequestionTF;
    private javax.swing.JLabel ownernameLbl;
    private javax.swing.JTextField ownernameTF;
    private javax.swing.JButton processqueueBtn;
    private javax.swing.JButton removeslotBtn;
    private javax.swing.JLabel slotidLbl;
    private javax.swing.JTextField slotidTF;
    private javax.swing.JLabel slotidupdateLbl;
    private javax.swing.JTextField slotidupdateTF;
    private javax.swing.JButton updateslotBtn;
    private javax.swing.ButtonGroup vehicleBG;
    private javax.swing.JLabel vehicleidLbl;
    private javax.swing.JTextField vehicleidTF;
    // End of variables declaration//GEN-END:variables
}
